# Для одной точки и 4 антенн (все в километрах и микросекундах)

In [31]:
import numpy as np
import numpy.linalg as linalg
import matplotlib.pyplot as plt
from itertools import combinations

In [44]:
a1 = np.array([-1., -1.])
a2 = np.array([1., -1.])
a3 = np.array([1., 1.])
a4 = np.array([-1., 1.])
a_arr = np.array([a1, a2, a3, a4])

t1 = 10
t2 = 12
t3 = 12
t4 = 13
t_arr = np.array([t1, t2, t3, t4], dtype=np.int64)
a_arr, t_arr

(array([[-1., -1.],
        [ 1., -1.],
        [ 1.,  1.],
        [-1.,  1.]]),
 array([10, 12, 12, 13]))

In [18]:
# CONST
V = 0.3

diff_pairs = np.array([np.array([2, 1]), np.array([3,2]),\
                       np.array([4, 3]), np.array([3,1]),\
                       np.array([4, 1]), np.array([4, 2])], dtype=np.int8)
diff_pairs

array([[2, 1],
       [3, 2],
       [4, 3],
       [3, 1],
       [4, 1],
       [4, 2]], dtype=int8)

In [116]:
g = []
for i in diff_pairs:
    a_i, a_j, t_i, t_j = a_arr[i[0]-1], a_arr[i[1]-1], t_arr[i[0]-1], t_arr[i[1]-1]
    g_ij = ((a_i[0] ** 2 + a_i[1] ** 2 - V ** 2 * t_i ** 2) - (a_j[0] ** 2 + a_j[1] ** 2 - V ** 2 * t_j ** 2))/2
    g.append(g_ij)
g = np.array(g, dtype=np.float64)
g

array([-1.98 ,  0.   , -1.125, -1.98 , -3.105, -1.125])

In [132]:
all_matrix = []
all_matrix_g = []
for i in combinations(diff_pairs, 3):
    diff_index = []
    diff_index_list = diff_pairs.tolist()
    diff_index.append(diff_index_list.index(i[0].tolist()))
    diff_index.append(diff_index_list.index(i[1].tolist()))
    diff_index.append(diff_index_list.index(i[2].tolist()))
    matrix = np.array([[a_arr[i[0][0]-1][0] - a_arr[i[0][1]-1][0],
                        a_arr[i[0][0]-1][1] - a_arr[i[0][1]-1][1],
                        t_arr[i[0][0]-1] - t_arr[i[0][1]-1]],
                       [a_arr[i[1][0]-1][0] - a_arr[i[1][1]-1][0],
                        a_arr[i[1][0]-1][1] - a_arr[i[1][1]-1][1],
                        t_arr[i[1][0]-1] - t_arr[i[1][1]-1]],
                       [a_arr[i[2][0]-1][0] - a_arr[i[2][1]-1][0],
                        a_arr[i[2][0]-1][1] - a_arr[i[2][1]-1][1],
                        t_arr[i[2][0]-1] - t_arr[i[2][1]-1]]])
    all_matrix.append(matrix)
    all_matrix_g.append(np.array(diff_index))
all_matrix = np.array(all_matrix)
all_matrix, all_matrix_g

(array([[[ 2.,  0.,  2.],
         [ 0.,  2.,  0.],
         [-2.,  0.,  1.]],
 
        [[ 2.,  0.,  2.],
         [ 0.,  2.,  0.],
         [ 2.,  2.,  2.]],
 
        [[ 2.,  0.,  2.],
         [ 0.,  2.,  0.],
         [ 0.,  2.,  3.]],
 
        [[ 2.,  0.,  2.],
         [ 0.,  2.,  0.],
         [-2.,  2.,  1.]],
 
        [[ 2.,  0.,  2.],
         [-2.,  0.,  1.],
         [ 2.,  2.,  2.]],
 
        [[ 2.,  0.,  2.],
         [-2.,  0.,  1.],
         [ 0.,  2.,  3.]],
 
        [[ 2.,  0.,  2.],
         [-2.,  0.,  1.],
         [-2.,  2.,  1.]],
 
        [[ 2.,  0.,  2.],
         [ 2.,  2.,  2.],
         [ 0.,  2.,  3.]],
 
        [[ 2.,  0.,  2.],
         [ 2.,  2.,  2.],
         [-2.,  2.,  1.]],
 
        [[ 2.,  0.,  2.],
         [ 0.,  2.,  3.],
         [-2.,  2.,  1.]],
 
        [[ 0.,  2.,  0.],
         [-2.,  0.,  1.],
         [ 2.,  2.,  2.]],
 
        [[ 0.,  2.,  0.],
         [-2.,  0.,  1.],
         [ 0.,  2.,  3.]],
 
        [[ 0.,  2.,  0.],
  

In [161]:
all_matrix_cond = []
for matrix in all_matrix:
    all_matrix_cond.append(linalg.cond(matrix))
min_cond = min(all_matrix_cond)

print(all_matrix_cond)

index = all_matrix_cond.index(min_cond)
print(min_cond, index)

main_matrix = all_matrix[index]
main_g = all_matrix_g[index].reshape(3,1)
main_matrix, main_g



[np.float64(1.5), np.float64(6.196043664933378e+16), np.float64(3.570522696696074), np.float64(2.715194527703128), np.float64(3.315951423753752), np.float64(3.982638731677844), np.float64(2.962712774714808), np.float64(4.725801483704863), np.float64(4.79921122275232), np.float64(1.8374018290473788e+16), np.float64(2.575130738580153), np.float64(2.765095172153138), np.float64(inf), np.float64(3.2324611573621667), np.float64(3.7421339903040467), np.float64(3.3699240762154807), np.float64(inf), np.float64(3.776668234305813), np.float64(3.9408633725811923), np.float64(5.979401699500051)]
1.5 0


(array([[ 2.,  0.,  2.],
        [ 0.,  2.,  0.],
        [-2.,  0.,  1.]]),
 array([[0],
        [1],
        [2]]))

In [159]:
x, y, _ = np.matmul(main_matrix, main_g).reshape(1,3).tolist()[0]
x, y

(4.0, 3.0)